export const LET_2025_TOP_SCHOOLS = [
  {
    rank: 1,
    school: "PNU - South Luzon",
    shortName: "PNU-SL",
    takers: 50,
    passed: 49,
    rate: 98.0,
  },
  {
    rank: 2,
    school: "Bicol University - Tabaco",
    shortName: "BU-Tabaco",
    takers: 64,
    passed: 62,
    rate: 96.88,
  },
  {
    rank: 3,
    school: "Limay Polytechnic College",
    shortName: "Limay PC",
    takers: 51,
    passed: 49,
    rate: 96.08,
  },
  {
    rank: 4,
    school: "Ilocos Sur Polytechnic State Col.",
    shortName: "ISPSC",
    takers: 97,
    passed: 93,
    rate: 95.88,
  },
  {
    rank: 5,
    school: "UP - Diliman",
    shortName: "UP-Diliman",
    takers: 54,
    passed: 51,
    rate: 94.44,
  },
  {
    rank: 6,
    school: "CSTC College of Sciences & Tech.",
    shortName: "CSTC",
    takers: 88,
    passed: 83,
    rate: 94.32,
  },
  {
    rank: 7,
    school: "E. L. Joson Memorial College",
    shortName: "ELJMC",
    takers: 79,
    passed: 73,
    rate: 92.41,
  },
  {
    rank: 8,
    school: "Cebu Tech University - Danao",
    shortName: "CTU-Danao",
    takers: 51,
    passed: 47,
    rate: 92.16,
  },
  {
    rank: 9,
    school: "Marinduque State University",
    shortName: "MarSU (Boac)",
    takers: 98,
    passed: 90,
    rate: 91.84,
    isTarget: true,
  },
];
