// Data extracted from the official 2025 Higher Education Program Licensure Report
export const LICENSURE_DATA = [
  {
    program: "LET Elementary",
    passed: 17,
    takers: 18,
    rate: 94,
    category: "Education",
  },
  {
    program: "LET Secondary",
    passed: 86,
    takers: 90,
    rate: 96,
    category: "Education",
  },
  {
    program: "Electronics Eng. (April)",
    passed: 10,
    takers: 15,
    rate: 67,
    category: "Engineering",
  },
  {
    program: "Electrical Eng. (April)",
    passed: 20,
    takers: 24,
    rate: 83,
    category: "Engineering",
  },
  {
    program: "Nursing (May)",
    passed: 5,
    takers: 5,
    rate: 100,
    category: "Health",
  },
  {
    program: "Fisheries",
    passed: 21,
    takers: 27,
    rate: 78,
    category: "Agriculture/Fisheries",
  },
  {
    program: "Agriculture",
    passed: 21,
    takers: 23,
    rate: 91,
    category: "Agriculture/Fisheries",
  },
  { program: "Midwifery", passed: 3, takers: 3, rate: 100, category: "Health" },
  {
    program: "Electronics Eng.",
    passed: 6,
    takers: 12,
    rate: 50,
    category: "Engineering",
  },
  {
    program: "Accountancy",
    passed: 4,
    takers: 4,
    rate: 100,
    category: "Business",
  },
  {
    program: "Social Work",
    passed: 52,
    takers: 56,
    rate: 93,
    category: "Humanities",
  },
  { program: "Nursing", passed: 89, takers: 94, rate: 95, category: "Health" },
  {
    program: "Civil Engineering",
    passed: 17,
    takers: 35,
    rate: 49,
    category: "Engineering",
  },
];
